### ISSUE TITLE
求教微调模型有没有办法可以改损失函数和评估函数呢

### ISSUE THREAD

**Issue by jarork** [ssbuild/baichuan2_finetuning#49]
我在搞一个agent，里面需要调用插件，如<插件名>插件输入<插件名>，我想在训练过程中评估插件的调用成功率，求教这个该怎么弄呢

**Comment by ssbuild** [comment]
不建议在训练过程中评估， 一旦参数不当巨慢，极大影响训练效率，还是建议评估改成离线评估

**Comment by ssbuild** [comment]
根据推理脚本 ， 可以按自己的需求写评估脚本

**Comment by jarork** [comment]
> 不建议在训练过程中评估， 一旦参数不当巨慢，极大影响训练效率，还是建议评估改成离线评估

我是想在训练的过程中选择一些比较优秀的存盘点，评估集不用很大。如果离线的话这存盘点太多了。还有就是在wandb上面的面板上能够看到更多有价值的评估指标的话可以便于优化。

**Comment by ssbuild** [comment]
你自己都说了评估集不用很大， 如何确保存储策略？ 这点评估数据能保证模型的指标吗
折腾来折腾去，感觉没必要。
